// Code generated by "stringer -type=compass"; DO NOT EDIT

package main

import "fmt"

const _compass_name = "NorthSouthEastWest"

var _compass_index = [...]uint8{0, 5, 10, 14, 18}

func (i compass) String() string {
	i -= 1
	if i < 0 || i >= compass(len(_compass_index)-1) {
		return fmt.Sprintf("compass(%d)", i+1)
	}
	return _compass_name[_compass_index[i]:_compass_index[i+1]]
}
